server:
  port: 9090

spring:
  datasource:
    username: root
    password: Anhdung1302
    url: jdbc:mysql://localhost:3307/spring_reactjs_jwt?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true


#    username: ubvgvfvergruflqk
#    password: FDSl99UuJgTtnsisAtqp
#    url: jdbc:mysql://bwmudlsuvrcglzdi5bw5-mysql.services.clever-cloud.com:3306/bwmudlsuvrcglzdi5bw5?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
