server:
  port: 9090

spring:
  datasource:
    username: ujkph9f2ajaviepn
    password: 1U97ZpBnnHPM4ujPjwMl
    url: jdbc:mysql://bt23zncfkffvszdx02zc-mysql.services.clever-cloud.com:3306/bt23zncfkffvszdx02zc?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true


#    username: ujkph9f2ajaviepn
#    password: 1U97ZpBnnHPM4ujPjwMl
#    url: jdbc:mysql://bt23zncfkffvszdx02zc-mysql.services.clever-cloud.com:3306/bt23zncfkffvszdx02zc?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
