server:
  port: 9090

spring:
  datasource:
    username: ucsq9oiwgrdgtdlf
    password: 3qAkwO9aXHzi45zx5Gzh
    url: jdbc:mysql://bjmdxbdrau4b9bnig6dp-mysql.services.clever-cloud.com:3306/bjmdxbdrau4b9bnig6dp?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false


  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true

#  username: root
#  password: Anhdung1302
#  url: jdbc:mysql://localhost:3307/spring_reactjs_jwt?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false